### ISSUE TITLE
sw_avb not working

### ISSUE THREAD

**Issue by nastasev** [xcore/sw_avb#14]
Hi there,

I'm a newbie with XMOS so please excuse my ignorance and delete my post if I'm missing the essence :-).

The latest version of app_xr_avb_lc_demo will not work properly unless you comment the following lines from avb_conf.h.
//#define MII_RX_BUFSIZE_HIGH_PRIORITY (700)
//#define MII_RX_BUFSIZE_LOW_PRIORITY (300)
//#define MII_TX_BUFSIZE_HIGH_PRIORITY (300)
//#define MII_TX_BUFSIZE_LOW_PRIORITY (200)

As far as I can see the defaults of these overrides are much higher and undersizing default buffers makes xtcp not working.

Maybe you'll take a look to this.

Thank you,
Virgil

**Comment by ghost** [comment]
Hi,
    Good point. These buffers need updating to work with the HEAD of the sc_ethernet module (I assume you are using the HEAD of sc_ethernet and that is the problem). I'll get this fixed.

Dave
