### ISSUE TITLE
Disassembly framework for XCore

### ISSUE THREAD

**Issue by aquynh** [xcore/sw_avb#30]
hi,

sorry if this is disturbing anybody, but we just want to make you aware of a XCore-related project: we just released Capstone, an open source disassembly framework for XCore (besides other archs such as Arm, Arm64, X86, Mips, etc).

our github is at https://github.com/aquynh/capstone, and website is at http://www.capstone-engine.org/

hopefully this is useful for XCore developers & community.

thanks.

**Comment by ajwlucas** [comment]
Thanks,

Looks interesting. Will take a closer look.
