### ISSUE TITLE
acmp_talker_valid_talker_unique bug!

### ISSUE THREAD

**Issue by g06i3351** [xcore/sw_avb#4]
Line 551 in avb_1722_1_acmp.c (module_avb_1722_1) should be changed to:

return acmp_talker_rcvd_cmd_resp.talker_unique_id < AVB_1722_1_MAX_TALKERS;

**Comment by ajwlucas** [comment]
Thanks Osedum, 

I will fix this bug as part of a bigger code restructuring this week.

**Comment by ajwlucas** [comment]
Fixed in 5.2.
